name: 'Infra CI'

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - develop
      - main
    paths:
      - '**.tf'
      - '**.tfvars'

jobs:
  terraform-files-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: set up terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.1

      - name: init
        run: terraform init
        working-directory: './eks'

      - name: validate
        run: terraform validate
        working-directory: './eks'

      - name: plan
        run: terraform plan
        working-directory: './eks'

      - name: apply
        run: terraform apply -auto-approve
        working-directory: './eks'

      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}
